// エンジニア職種とスキルベクトルのマッピング（5次元のスキルマップ）
export const careerVectors = {
  TechLead: {
    programming: 4,
    softwareDevelopment: 5,
    database: 4,
    systemDesign: 5,
    communication: 5,
    teamwork: 4,
    leadership: 5,
    label: "テックリード",
  },
  EngineeringManager: {
    programming: 3,
    softwareDevelopment: 4,
    database: 3,
    systemDesign: 4,
    communication: 5,
    teamwork: 5,
    leadership: 5,
    label: "エンジニアリングマネージャー",
  },
  ProductManager: {
    programming: 2,
    softwareDevelopment: 2,
    database: 2,
    systemDesign: 3,
    communication: 5,
    teamwork: 5,
    leadership: 4,
    label: "プロダクトマネージャー",
  },
  DevOpsEngineer: {
    programming: 3,
    softwareDevelopment: 4,
    database: 4,
    systemDesign: 4,
    communication: 3,
    teamwork: 4,
    leadership: 3,
    label: "DevOpsエンジニア",
  },
  FullStackDeveloper: {
    programming: 5,
    softwareDevelopment: 4,
    database: 4,
    systemDesign: 3,
    communication: 3,
    teamwork: 4,
    leadership: 2,
    label: "フルスタックエンジニア",
  },
  FrontendDeveloper: {
    programming: 3,
    softwareDevelopment: 3,
    database: 2,
    systemDesign: 2,
    communication: 3,
    teamwork: 4,
    leadership: 2,
    label: "フロントエンドエンジニア",
  },
  BackendDeveloper: {
    programming: 4,
    softwareDevelopment: 4,
    database: 5,
    systemDesign: 4,
    communication: 3,
    teamwork: 4,
    leadership: 2,
    label: "バックエンドエンジニア",
  },
  MobileEngineer: {
    programming: 4,
    softwareDevelopment: 3,
    database: 2,
    systemDesign: 3,
    communication: 3,
    teamwork: 4,
    leadership: 2,
    label: "モバイルエンジニア",
  },
} as const;
